apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  backend:
    serviceName: nginx
    servicePort: 4000
  rules:
    - http:
        paths:
        - path: /api/*
          backend:
            serviceName: api
            servicePort: 3000
